#!/usr/bin/env bash

set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

glslc shaders/shader.vert -o vert.spv
glslc shaders/shader.frag -o frag.spv
